# Generated by Django 5.1.7 on 2026-02-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='image',
        ),
    ]
