# Generated by Django 5.1.7 on 2026-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_remove_festival_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='famous_dance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='state',
            name='famous_food',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='state',
            name='famous_temple',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
