# Generated by Django 5.1.7 on 2026-02-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_state_famous_dance_state_famous_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='famous_folk_art',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='monuments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='traditional_dress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='uniqueness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='famous_dance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='famous_food',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='famous_for',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='famous_temple',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('famous_food', models.TextField(blank=True)),
                ('famous_festival', models.TextField(blank=True)),
                ('famous_temple', models.TextField(blank=True)),
                ('famous_monument', models.TextField(blank=True)),
                ('uniqueness', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.state')),
            ],
        ),
    ]
