# Generated by Django 5.1.7 on 2026-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_state_famous_folk_art_state_monuments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='famous_for',
        ),
        migrations.AddField(
            model_name='state',
            name='dance_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='dress_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='folk_art_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='food_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='monument_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='temple_image',
            field=models.URLField(blank=True),
        ),
    ]
