# Generated by Django 5.1.7 on 2026-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
