# Generated by Django 5.1.7 on 2026-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('external_link', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
