# Generated by Django 5.1.7 on 2026-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0009_culturalitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CulturalItem',
        ),
        migrations.RemoveField(
            model_name='district',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='district',
            name='longitude',
        ),
        migrations.AddField(
            model_name='district',
            name='festival_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='district',
            name='food_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='district',
            name='monument_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='district',
            name='temple_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='dance_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='dress_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='folk_art_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='food_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='monument_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='temple_link',
            field=models.URLField(blank=True),
        ),
    ]
