# Generated by Django 5.1.7 on 2026-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0010_delete_culturalitem_remove_district_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='uniqueness_link',
            field=models.URLField(blank=True),
        ),
    ]
