# Generated by Django 5.1.7 on 2026-06-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0011_district_uniqueness_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('state', 'State'), ('district', 'District')], max_length=20)),
                ('state_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
