# Generated by Django 5.1.7 on 2026-06-08 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0012_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.AddField(
            model_name='submission',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='dance_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dance_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dress_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dress_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='famous_dance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='famous_festival',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='famous_folk_art',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='famous_food',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='famous_temple',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='festival_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='folk_art_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='folk_art_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='food_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='food_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='monument_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='monument_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='monuments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='temple_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='temple_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='traditional_dress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='uniqueness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='uniqueness_link',
            field=models.URLField(blank=True),
        ),
    ]
