# Generated by Django 5.1.7 on 2026-06-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0013_remove_submission_category_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='unique_district_per_state'),
        ),
    ]
